---
- include: tasks/init-debian.yml
  when: ansible_os_family == 'Debian'
- include: tasks/init-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Run configured pre-provision shell scripts.
  script: "{{ item }}"
  with_items: "{{ pre_provision_scripts|default([]) }}"

- name: Run configured pre-provision ansible task files.
  include: "{{ item }}"
  with_fileglob:
    - "{{ pre_provision_tasks_dir|default(omit) }}"

- include: sshd.yml
- include: extras.yml
- include: www.yml
- include: apparmor.yml
  when: ansible_os_family == 'Debian'

- name: Run configured post-provision shell scripts.
  script: "{{ item }}"
  with_items: "{{ post_provision_scripts|default([]) }}"

- name: Run configured post-provision ansible task files.
  include: "{{ item }}"
  with_fileglob:
    - "{{ post_provision_tasks_dir|default(omit) }}"
